### PR TITLE
Fix type metadata lookup and arity detection for nested type wrappers

### LINKED ISSUE #6: Type metadata lookup and arity detection fail for nested type wrappers
# Type metadata lookup and arity detection fail for nested type wrappers

When GraphQL fields use nested type wrappers like `non_null(list_of(non_null(:type)))`, two bugs occur:

1. Type metadata lookup fails - can't retrieve `permit()` metadata from types
2. Arity detection fails - list queries incorrectly use single-record loading (`:one` instead of `:all`)

These bugs affect all code paths:
- Direct resolver: `resolve(&PermitAbsinthe.load_and_authorize/2)`
- Middleware: `middleware Permit.Absinthe.Middleware.LoadAndAuthorize`
- Directive: `directives: [:load_and_authorize]`

### Bug 1: single-level type unwrapping in meta.ex

`lib/permit_absinthe/schema/meta.ex` only unwraps one level:

```elixir
type_ref =
  case schema_node.type do
    %{of_type: inner_type} -> inner_type
    other -> other
  end
```

For `non_null(list_of(non_null(:note)))`, this produces:
```
%Absinthe.Type.List{of_type: %Absinthe.Type.NonNull{of_type: :note}}
```

Calling `schema.__absinthe_type__(type_ref)` with a non-atomic type reference returns `nil`, causing:
```
** (KeyError) key :__private__ not found in: nil
```

### Bug 2: single-level list detection in load_and_authorize.ex

`lib/permit_absinthe/load_and_authorize.ex` only checks the top level:

```elixir
defp determine_arity(resolution) do
  with %{definition: %{schema_node: schema_node}} <- resolution do
    case schema_node.type do
      %Absinthe.Type.List{} -> :all
      _ -> :one
    end
  else
    _ -> :one
  end
end
```

For `non_null(list_of(...))`, the top level is `NonNull`, not `List`, so it returns `:one`, causing:
```
** (Ecto.MultipleResultsError) expected at most one result but got 2
```

### The directive doesn't help

The `:load_and_authorize` directive in `lib/permit_absinthe/schema/prototype.ex` calculates arity during schema compilation:

```elixir
arity =
  case node.type do
    %Absinthe.Blueprint.TypeReference.List{} -> :all
    _ -> :one
  end

%{node | middleware: [{Permit.Absinthe.Middleware.LoadAndAuthorize, arity} | existing]}
```

However, the middleware completely ignores this parameter:

```elixir
def call(resolution, _) do  # arity parameter discarded
  case LoadAndAuthorize.load_and_authorize(resolution.arguments, resolution) do
    # ...
  end
end
```

The middleware calls `LoadAndAuthorize.load_and_authorize/2` which re-determines arity using the same buggy `determine_arity/1` function, so the directive's calculation is wasted.

## Steps to reproduce

Define a schema following GraphQL best practices:

```elixir
object :note do
  field :id, non_null(:id)
  field :name, non_null(:string)
  permit(schema: Note)
end

query do
  # using directive
  field :notes, non_null(list_of(non_null(:note))), directives: [:load_and_authorize] do
    permit(action: :read)
    resolve(fn _, _, %{context: %{loaded_resources: notes}} -> {:ok, notes} end)
  end
  
  # or using direct resolver
  field :notes_alt, non_null(list_of(non_null(:note))) do
    permit(action: :read)
    resolve(&PermitAbsinthe.load_and_authorize/2)
  end
  
  # or using middleware
  field :notes_alt2, non_null(list_of(non_null(:note))) do
    permit(action: :read)
    middleware Permit.Absinthe.Middleware.LoadAndAuthorize
    resolve(fn _, _, %{context: %{loaded_resources: notes}} -> {:ok, notes} end)
  end
end
```

Execute query: `{ notes { id name } }` and observe errors.

### Fix 1: recursive type unwrapping in meta.ex

Add helper function:
```elixir
defp unwrap_type(%{of_type: inner_type}), do: unwrap_type(inner_type)
defp unwrap_type(type), do: type
```

Update functions:
```elixir
def get_type_meta_from_resolution(resolution, meta_keys) when is_list(meta_keys) do
  with %{definition: %{schema_node: schema_node}, schema: schema} <- resolution do
    type_ref = unwrap_type(schema_node.type)
    type = schema.__absinthe_type__(type_ref)
    
    case type do
      nil ->
        nil
      type ->
        case type.__private__ do
          nil -> nil
          private -> get_in(private[:meta] || [], meta_keys)
        end
    end
  else
    _ -> nil
  end
end

def get_type_name(resolution) do
  with %{definition: %{schema_node: schema_node}} <- resolution do
    unwrap_type(schema_node.type)
  else
    _ -> nil
  end
end
```

### Fix 2: recursive list detection in load_and_authorize.ex

```elixir
defp determine_arity(resolution) do
  with %{definition: %{schema_node: schema_node}} <- resolution do
    if has_list_type?(schema_node.type), do: :all, else: :one
  else
    _ -> :one
  end
end

defp has_list_type?(%Absinthe.Type.List{}), do: true
defp has_list_type?(%{of_type: inner_type}), do: has_list_type?(inner_type)
defp has_list_type?(_), do: false
```

### Optional fix 3: actually use the directive's arity calculation

This would be a breaking change. Update middleware to accept and use the arity parameter:

```elixir
def call(resolution, arity) when arity in [:one, :all] do
  case LoadAndAuthorize.load_and_authorize(resolution.arguments, resolution, arity) do
    # ...
  end
end

def call(resolution, _), do: call(resolution, :one)  # backward compat
```

Then add a 3-arity version of load_and_authorize that accepts pre-determined arity.

## Impact

The library is unusable with standard GraphQL best practices - any field using `non_null(...)` wrapper on return types or list queries with `non_null(list_of(...))` will fail. This affects most real-world GraphQL schemas.

## Why the tests didn't catch this

The test suite uses simpler type structures:

```elixir
field :item, :item                    # no NonNull wrapper
field :items, list_of(:item)          # no outer NonNull wrapper
```

These create simple type structures that single-level unwrapping handles:
- `:item` - already unwrapped
- `%List{of_type: :item}` - one unwrap gets to `:item`

Real-world schemas following GraphQL best practices use:
```elixir
field :note, non_null(:note)                      # %NonNull{of_type: :note}
field :notes, non_null(list_of(non_null(:note)))  # nested 3 levels deep
```

## Recommended test additions

- Test with `non_null(:type)` return types
- Test with `non_null(list_of(non_null(:type)))` (GraphQL best practice)
- Test with `list_of(non_null(:type))`
- Test all three code paths (directive, middleware, direct resolver)
- Test arity detection explicitly for wrapped lists

## Environment

- Elixir 1.18.4
- Absinthe 1.9.0
- permit_absinthe 0.1.0
- Ecto 3.13.5

### PR DESCRIPTION
**Pull request by vincentvanbush**
Fixes #6

This PR addresses two critical bugs in permit_absinthe that occur when using nested type wrappers like `non_null(list_of(non_null(:type)))`:

### 1. Type metadata lookup bug (lib/permit_absinthe/schema/meta.ex)

**Problem:**
- Single-level type unwrapping failed with nested NonNull/List structures
- Caused `KeyError` when accessing `type.__private__` on nil types

**Solution:**
- Added recursive `unwrap_type/1` helper to fully unwrap all type wrappers
- Added nil guards to prevent KeyError when type lookup fails

### 2. Arity detection bug (lib/permit_absinthe/load_and_authorize.ex)

**Problem:**
- Top-level pattern matching missed List types wrapped in NonNull
- Caused `Ecto.MultipleResultsError` when list queries incorrectly used `:one` arity

**Solution:**
- Added recursive `has_list_type?/1` to detect List at any nesting level
- Extracted arity detection into `determine_arity/1` helper function

## Impact

These bugs affected all code paths (directive, middleware, direct resolver) and caused production errors with queries using nested type wrappers, which are common in GraphQL best practices.

## Testing

Verified with real GraphQL queries using nested type wrappers:
- `notes { id name comments { id title } }` - list query with nested types
- `note(id: 1) { id name comments { id title } }` - single resource with nested types
- All queries return correct results with proper authorization

### CODE REVIEW

File: lib/permit_absinthe/load_and_authorize.ex [hunk 1]
```diff
@@ -78,4 +74,17 @@ defmodule Permit.Absinthe.LoadAndAuthorize do
         {:error, "Not found"}
```
Comment (itamm15) [inline lib/permit_absinthe/load_and_authorize.ex:74]: I know this is out of the scope of this PR, but IMHO it would be better to return `atoms`, rather than `strings`, e.g. `{:error, :not_found}` (and the consumer can easily match on `atom` and return a custom message).

File: lib/permit_absinthe/load_and_authorize.ex [hunk 2]
```diff
@@ -78,4 +74,17 @@ defmodule Permit.Absinthe.LoadAndAuthorize do
...
     end
   end
+
+  defp determine_arity(resolution) do
+    with %{definition: %{schema_node: schema_node}} <- resolution do
+      if has_list_type?(schema_node.type), do: :all, else: :one
+    else
+      _ -> :one
+    end
+  end
```
Comment (itamm15) [inline lib/permit_absinthe/load_and_authorize.ex]: nit:
```elixir
defp determine_arity(%{definition: %{schema_node: schema_node}}) do
  if has_list_type?(schema_node.type), do: :all, else: :one
end

defp determine_arity(_), do: :one
```

**Review by itamm15 — APPROVED** [review]

File: lib/permit_absinthe/load_and_authorize.ex (hunk 1 above)
Comment (vincentvanbush) [reply lib/permit_absinthe/load_and_authorize.ex:74]: I'm not sure Absinthe allows that - will check it out tho
